# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0002_todolist_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
