# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 00:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0004_remove_task_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(default=datetime.datetime(2017, 5, 24, 20, 40, 54, 416000)),
        ),
    ]
