# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 13:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('simpleChecklist', '0009_auto_20170525_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterUniqueTogether(
            name='todolist',
            unique_together=set([('name', 'user')]),
        ),
    ]
