# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-26 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0010_auto_20170526_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
