# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-01 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0011_auto_20170526_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('3', 'Low'), ('2', 'Normal'), ('1', 'High')], default='2', max_length=1),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
