# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0012_auto_20170601_1213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('1', 'Low'), ('2', 'Normal'), ('3', 'High')], default='2', max_length=1),
        ),
    ]
