# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0013_auto_20170603_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='task',
            name='note',
            field=models.TextField(max_length=40),
        ),
    ]
