# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 14:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleChecklist', '0014_auto_20170603_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='name',
            field=models.CharField(max_length=35),
        ),
    ]
